server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: webhook-management
  
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=webhook_db;encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:YourPassword123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    defer-datasource-initialization: true
    
  sql:
    init:
      mode: always
      
  security:
    user:
      name: admin
      password: password
      roles: ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.webhookdemo: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE